### ISSUE TITLE
[Bug] on openEuler 22.03 (LTS-SP4) system, cloudberrydb-1.6.0 install with source code ,error occured when gpinitsystem 

### ISSUE THREAD

**Issue by fsmiledream** [apache/cloudberry#620]
### Cloudberry Database version

cloudberrydb-1.6.0 

### What happened

20240906:18:23:28:112430 gpinitsystem:cloudberrydb1:gpadmin-[INFO]:-No errors generated from parallel processes
20240906:18:23:28:112430 gpinitsystem:cloudberrydb1:gpadmin-[INFO]:-Restarting the CloudberryDB instance in production mode
Traceback (most recent call last):
  File "/usr/local/cloudberrydb/bin/gpstop", line 9, in <module>
    from gppylib.mainUtils import *
  File "/usr/local/cloudberrydb/lib/python/gppylib/mainUtils.py", line 31, in <module>
    from gppylib.commands import gp, unix
  File "/usr/local/cloudberrydb/lib/python/gppylib/commands/gp.py", line 22, in <module>
    from gppylib.db import dbconn
  File "/usr/local/cloudberrydb/lib/python/gppylib/db/dbconn.py", line 15, in <module>
    from gppylib.commands.unix import UserId
  File "/usr/local/cloudberrydb/lib/python/gppylib/commands/unix.py", line 17, in <module>
    from gppylib.commands.base import *
  File "/usr/local/cloudberrydb/lib/python/gppylib/commands/base.py", line 32, in <module>
    from pg import DB
  File "/usr/local/lib/python3.9/site-packages/pg/__init__.py", line 3
    async,
    ^
SyntaxError: invalid syntax
20240906:18:23:28:112430 gpinitsystem:cloudberrydb1:gpadmin-[FATAL]:-Error from CloudberryDB instance shutdown, check log files Script Exiting!

![cbdb1 6 0+openruler22 03 initsystem error](https://github.com/user-attachments/assets/15881bb1-ab2d-4077-9a41-968e89d662f6)

### How to reproduce

The err is the same as 1.5.4 with rpm/source . now 1.6.0rpm is repaired，but 1.6.0 install with source code is still same error

### Operating System

openEuler 22.03 (LTS-SP4)

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://cloudberrydb.org/community/coc).

**Comment by tuhaihe** [comment]
Hi @Zhangbaowen-Hashdata @edespino could you help take a look? Thanks.

**Comment by yihong0618** [comment]
try:

pip3 uninstall pg
pip3 install -U PyGreSQL
then
gpstop -ar

**Comment by yihong0618** [comment]
solution

pip3 uninstall pg
pip3 uninstall PyGreSQL

then
pip3 install -U PyGreSQL

**Comment by yihong0618** [comment]
> solution
> 
> pip3 uninstall pg pip3 uninstall PyGreSQL
> 
> then pip3 install -U PyGreSQL

------

we can reproduce this by

pip3 uninstall pg
pip3 uninstall PyGreSQL

then 
pip3 install -U PyGreSQL
pip3 install pg

then error happened

then use the solution can fix this.

**Comment by avamingli** [comment]
> solution
> 
> pip3 uninstall pg pip3 uninstall PyGreSQL
> 
> then pip3 install -U PyGreSQL

Thanks @yihong0618 .
Generally, I think we need to update XXX.dependency if XXX is officially supported. 
@tuhaihe @Zhangbaowen-Hashdata Could anyone you help to track this, thanks.

**Comment by fsmiledream** [comment]
@yihong0618 Thank you very much! Using your solution ,I can also initsystem successfully.
 I also hope source code can be fixed and updated .

**Comment by tuhaihe** [comment]
Thanks @yihong0618 ! I think we should update the doc on building from source code.

**Comment by gongxun0928** [comment]
@tuhaihe @avamingli  The installation of Python dependencies for Ubuntu is different from other OS systems. We need to use `pip3 install -r ../../python-dependencies.txt` like [Readme.CentOS.bash.](https://github.com/cloudberrydb/cloudberrydb/blob/main/deploy/build/README.CentOS.bash#L34) In this way, Python dependencies will use a fixed version instead of relying on the version in the apt source.

**Comment by avamingli** [comment]
> @tuhaihe @avamingli @Zhangbaowen-Hashdata We need to use `pip3 install -r ../../python-dependencies.txt` like [Readme.CentOS.bash.](https://github.com/cloudberrydb/cloudberrydb/blob/main/deploy/build/README.CentOS.bash#L34) In this way, Python dependencies will use a fixed version instead of relying on the version in the apt source.

+1, that's what I suggest.
We should be clear which OS is officially supported(probably Release team knows well about it) , update xxx_dependencies.txt by the way,

**Comment by my-ship-it** [comment]
@Zhangbaowen-Hashdata, Hi Baowen, could you please try the suggestions above?

**Comment by Zhangbaowen-Hashdata** [comment]
> @Zhangbaowen-Hashdata, Hi Baowen, could you please try the suggestions above?

I will conduct a verification locally first, and if there are no issues, I will provide a safety check.

**Comment by yjhjstz** [comment]
> > @Zhangbaowen-Hashdata, Hi Baowen, could you please try the suggestions above?
> 
> I will conduct a verification locally first, and if there are no issues, I will propose a new PR.

any progress ?

**Comment by Baowen648** [comment]
I've raised the PR need to wait for the merger.
https://github.com/apache/cloudberry/pull/664
