### ISSUE TITLE
[Bug] New partition options are inherited from the parent table rather than specified through GUC variables

### ISSUE THREAD

**Issue by congxuebin** [apache/cloudberry#758]
### Apache Cloudberry version

Cloudberry Database 1.0.0+47f626c build commit:47f626c6cc7fc6a7dd320e0c170f133a33b69952

### What happened

Failed Test Cases
```
DefaultStorageParameterTestCase.test_partition_tables ... 7039.52 ms ... FAIL

======================================================================

FAIL: DefaultStorageParameterTestCase.test_partition_tables
----------------------------------------------------------------------
Traceback (most recent call last):
File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 489, in implied_test_function
result = my_self.run_test()
File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 668, in run_test
self._run_and_verify_sql_file(sql_file, self._current_optimizer_mode)
File "/code/cbdb_testrepo_src/mpp/models/sql_tc.py", line 725, in _run_and_verify_sql_file
ans_file))
AssertionError: Failed: diffs during execution of sql: /code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/sql/partition_tables.sql, out_file: /code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/output/partition_tables.out, ans_file: /code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/partition_tables.ans

----------------------------------------------------------------------
Ran 112 tests in 351.781s

FAILED (failures=1, skipped=23)
```

```
Drop table if exists ap_pr_t02;
psql:/code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/output/partition_tables.sql:39: NOTICE:  table "ap_pr_t02" does not exist, skipping
DROP TABLE
Create table ap_pr_t02( i int, j int, k int) with(appendonly=false) partition by range(i) (start(1) end(10) every(5));
psql:/code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/output/partition_tables.sql:40: NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i' as the Cloudberry Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
Insert into ap_pr_t02 select i, i+1, i+2 from generate_series(1,9) i;
INSERT 0 9
Select count(*) from ap_pr_t02;
psql:/code/cbdb_testrepo_src/mpp/gpdb/tests/storage/access_methods/storage_parameters/output/partition_tables.sql:43: NOTICE:  One or more columns in the following table(s) do not have statistics: ap_pr_t02
HINT:  For non-partitioned tables, run analyze <table_name>(<column_list>). For partitioned tables, run analyze rootpartition <table_name>(<column_list>). See log for columns missing statistics.
 count 
-------
     9
(1 row)

SET default_table_access_method='ao_row';
SET
SET gp_default_storage_options="compresstype=quicklz";
SET
show default_table_access_method;
 default_table_access_method 
-----------------------------
 ao_row
(1 row)

show gp_default_storage_options;
                     gp_default_storage_options                     
--------------------------------------------------------------------
 blocksize=32768,compresstype=quicklz,compresslevel=1,checksum=true
(1 row)

Alter table ap_pr_t02 add partition p3 start(11) end(15);
ALTER TABLE

```
Actual result:

```
select relkind, reloptions from pg_class where relname like 'ap_pr_t02%';
 relkind | reloptions 
---------+------------
 p       | 
 r       | 
 r       | 
 r       | 
(4 rows)
```

Expected result:
```
select relkind, reloptions from pg_class where relname like 'ap_pr_t02%';
 relkind |       reloptions       
---------+------------------------
 p       | 
 r       | 
 r       | 
 r       | {compresstype=quicklz}
(4 rows)

```

### How to reproduce

As above said

### Operating System

centos7

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

**Comment by congxuebin** [comment]
Likely related to https://github.com/apache/cloudberry/pull/695

**Comment by congxuebin** [comment]
We also have these failures likely related to #695. Can you please confirm as well? 

[testrepo_failures.zip](https://github.com/user-attachments/files/18021104/testrepo_failures.zip)

**Comment by gfphoenix78** [comment]
It's expected behavior. The inherited options is prior to the GUC variables.
